### ISSUE TITLE
NuGet tool

### ISSUE THREAD

**Issue by lithiumtoast** [lithiumtoast/c2cs#14]
TODO:
- [ ] Setup workflow automation for building and deploying C2CS command line program as NuGet tool; triggered by new release tag
- [ ] Update README with how to get/use C2CS using NuGet tool

**Comment by lithiumtoast** [comment]
Workflow automation is setup for Linux only right now. Problem is that `libclang` native library is quite large (~30mb) for each platform. It doesn't make much sense to have a NuGet package which is ~100mb.

Additionally GitHub packages is currently blocking an ideal solution where anybody can download the package. Right now people have to create a personal access token (PAT) to be able to download packages from GitHub; what a mess.

**Comment by lithiumtoast** [comment]
Will not support NuGet tool moving forward.

**Comment by panda-roux-dev** [comment]
I notice that generated source files include a `using C2CS;` directive.

I want to be able to simply copy the generated C# source file into my project, but I have no idea where that `C2CS` namespace is meant to come from.  If it's not in a Nuget package that's very inconvenient.

**Comment by lithiumtoast** [comment]
Oh, this ticket was specifically about `C2CS` as a "tool". If you want I can package `C2CS.Runtime` as a NuGet package. I actually previously had it packaged. I deploy to https://www.myget.org/feed/lithiumtoast/package/nuget/C2CS.Runtime to which I still have a package from last week.

**Comment by lithiumtoast** [comment]
Another option is you can just copy the files found here: https://github.com/lithiumtoast/c2cs/tree/develop/src/cs/production/C2CS.Runtime

**Comment by panda-roux-dev** [comment]
My mistake then!

That would be very helpful, thank you.
