### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by longjoel** [lithiumtoast/c2cs#4]
Error	CS0246	The type or namespace name 'GeneratePlatformInvokeCodeUseCase' could not be found (are you missing a using directive or an assembly reference?)	C2CS.CommandLine

Error	CS0246	The type or namespace name 'CodeCParser' could not be found (are you missing a using directive or an assembly reference?)	C2CS.CommandLine

**Comment by lithiumtoast** [comment]
Did you init/pull Git submodules?

**Comment by longjoel** [comment]
no, I just downloaded the .zip. I will try cloning it and seeing if that works.

**Comment by lithiumtoast** [comment]
@longjoel Did you figure it out?

**Comment by lithiumtoast** [comment]
I learned that Git submodules with SSH (`git@`) doesn't work for some people; I switched it to use HTTPS instead
