### ISSUE TITLE
Wrap into namespace

### ISSUE THREAD

**Issue by CBenoit** [lithiumtoast/c2cs#46]
Hi,

It appears we can't tell the tool to wrap the resulting class into a namespace such as:

```c#
namespace Devolutions.Picky { // <---- here
  //-------------------------------------------------------------------------------------
  // <auto-generated>
  //     This code was generated by the following tool:
  //        https://github.com/lithiumtoast/c2cs (v0.0.0.0)
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
  // ReSharper disable All
  //-------------------------------------------------------------------------------------
  using System;
  using System.Runtime.InteropServices;
  using System.Runtime.CompilerServices;
  
  using C2CS;
  
  #nullable enable
  #pragma warning disable 1591
  
  public static unsafe partial class Native
  {
      private const string LibraryName = "picky";
  
      // Function @ picky.h:24:6 (/home/…)
      [DllImport(LibraryName)]
      public static extern void picky_clear_last_error();
  
      …
  }
}
```

or

```c#
namespace Devolutions.Picky; // <-- prepend
```

I think a new `--namespace` argument to the `cs` subcommand could be useful for that.

Cheers

**Comment by lithiumtoast** [comment]
Hmm, okay, as an option this is a good idea.

With P/Invoke, do you import the whole static class? Like `using static Devolutions.Picky.Native`?

**Comment by CBenoit** [comment]
I do not import the whole static class, but I use it from the other wrapping safe classes like so:

```c#
using C2CS;

namespace Devolutions.Picky;

public static class Pem
{
  public static extern Pem Parse(String input) {
      int inputSz = input.Length;
      CStringU8 cInput = new CStringU8(input);
     
      unsafe {
        // `Native` is in the same namespace
        Native.picky_pem_t *pem = Native.picky_pem_parse(cInput, inputSz);

        // … build a `Pem` object…
      }
  }

  …
}
```

The user will simply use the safe wrapper `Devolutions.Picky.Pem` (and others), but may also use the low-level unsafe primitives from `Devolutions.Picky.Native` if required.

**Comment by lithiumtoast** [comment]
Oh, do you write some "safe" version of functions by hand?

**Comment by CBenoit** [comment]
Yes, exactly!

**Comment by lithiumtoast** [comment]
Okay, that's interesting. Do you think Is there room for improvement in terms of auto-generating code for "safe" version of the functions?

**Comment by CBenoit** [comment]
Hmm… I'm not really sure as I hardly see how the safe code could be generated easily given an arbitrary C API.

Let's take this prototype that I have in my project:
```c
/**
 * Creates a PEM object with a copy of the data.
 */
struct picky_pem_t *picky_pem_new(const char *label,
                                  int label_sz,
                                  const uint8_t *data,
                                  int data_sz);

```

Technically, I don't really need the `label_sz` argument as long as `label` is NULL-terminated, but, "better safe than sorry", I prefer to always specify the max size to read from the buffer.

So, I need to call the API with the following C# code:

```c#
// --- Pem.cs --- //
namespace Devolutions.Picky;

public class Pem
{
    private unsafe Native.picky_pem_t* inner = null;

    public Pem(String label, byte[] data)
    {
        byte[] utf8Label = Utils.StringToUtf8WithNulTerminator(label);

        unsafe
        {
            fixed (byte* utf8LabelPtr = utf8Label, dataPtr = data)
            {
                this.inner = Native.Raw.pem_new(utf8LabelPtr, utf8Label.Length, dataPtr, data.Length);

                if (this.inner == null)
                {
                    throw new /* some exception */;
                }

                this.label = label;
                this.data = data;
            }
        }
    }

    // --- cut --- //
}
```

My native library is working with UTF-8, so I convert with a helper class:

```c#
// --- Utils.cs --- //
using System.Text;

namespace Devolutions.Picky;

public static class Utils
{
    public static byte[] StringToUtf8WithNulTerminator(String s)
    {
        int size = Encoding.UTF8.GetByteCount(s) + 1;
        byte[] buf = new byte[size];
        Encoding.UTF8.GetBytes(s, 0, s.Length, buf, 0);
        buf[size - 1] = 0; // make sure we have a C-style nul-byte
        return buf;
    }

    public static String Utf8WithNulTerminatorToString(byte[] utf8)
    {
        int size_without_nul = utf8.Length - 1;
        char[] chars = new char[size_without_nul];
        Encoding.UTF8.GetChars(utf8, 0, size_without_nul, chars, 0);
        return new String(chars);
    }
}
```

In the case of `picky_pem_new` the special return value for an error is `null`, but in other cases such as this one:

```c
/**
 * Copy the label associated to the data contained in the PEM object.
 *
 * Returns the number of bytes written, or `-1` if there was an error.
 */
int picky_pem_label(const struct picky_pem_t *this_, char *label, int label_sz);
```

The special value is `-1` and calling code must handle the result accordingly.

I'm not sure how we can convey the generator:
- what is the special value to handle error cases,
- and what is the expected encoding of the strings.

As it can't really be properly encoded in the C type system.

I guess it would require binding directly a "higher-level" language such as C++ or Rust (like [`cxx`](https://github.com/dtolnay/cxx) for Rust/C++ or [`interoptopus`](https://github.com/ralfbiedert/interoptopus))

So, I think it's probably out of scope for `C2CS`. I don't know if this helps haha

**Comment by lithiumtoast** [comment]
Done in #49

**Comment by CBenoit** [comment]
Looks good, thank you!
