### ISSUE TITLE
Empty generation

### ISSUE THREAD

**Issue by wobes1** [lithiumtoast/c2cs#7]
Hello there,

I hope this message finds you well. First of all, thank you for your work! I was able to build the generator and test it out, however I think there is something I miss. The generator generates empty classes i.e sokol_gfx, is there something that I miss? 

![image](https://user-images.githubusercontent.com/24993673/107878251-487dee00-6e9f-11eb-9fea-5b8246fc31a4.png)

**Comment by lithiumtoast** [comment]
Something is for sure not right.

What os+arch you using?
What parameters are you using?

I use the following parameters for `sokol_gfx.h` on macOS:

```bash
-i
"/Users/lstranks/Programming/sokol/sokol_gfx.h"
-o
"./sokol_gfx.cs"
-u
-l
"sokol_gfx"
-s
"/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include"
```

Output: https://www.dropbox.com/s/melgx7wv2ida8lt/sokol_gfx.cs?dl=0

**Comment by wobes1** [comment]
Windows 10 x64, can it be due to -s parameter that needs to be specified? I tried with -s and clang include path the output is the same. 

_C2CS.CommandLine.exe -i "sokol_gfx.h" -o "test.cs" -u -l "sokol_gfx"_

**Comment by lithiumtoast** [comment]
Interesting just tested on Windows 10 Home 64-bit (10.0, Build 18363), and it works

```bash
-i
"C:\Users\lustr\Programming\sokol\sokol_gfx.h"
-o
"./sokol_gfx.cs"
-u
-l
"sokol_gfx"
```

Did you copy  `C2CS.CommandLine.exe` to somewhere? I usually just use the tool from the bin directory `.\bin\C2CS.CommandLine\Debug\net5.0`

**Comment by lithiumtoast** [comment]
I'll probably take this opportunity as a hint that I need some CI/CD.

**Comment by wobes1** [comment]
No no, I used it from the bin directory. Is -s parameter mandatory or the generator should work without it?

**Comment by lithiumtoast** [comment]
The `-s` is for include directories. I would think you would only need to do use it if `libclang` reported a missing header like:

```bash
fatal error: 'stdint.h' file not found
```
What's the command line output? Is there any clang diagnostics printed to stdout or stderr?

**Comment by wobes1** [comment]
Ah I see. No errors reported 
![image](https://user-images.githubusercontent.com/24993673/107881998-f942b800-6eb4-11eb-9031-fb62dacf1f7c.png)

**Comment by lithiumtoast** [comment]
May seem dumb, but what are the contents of `sokol_gfx.h`? That file is copied to bin directory? I usually just pass the full path to the `sokol` git repository like: `C:\Users\lustr\Programming\sokol\sokol_gfx.h`

**Comment by wobes1** [comment]
Uff, that was it. I had not only sokol_gfx but other headers, but as soon as I specified the git path it all worked. Thank you so much.
![image](https://user-images.githubusercontent.com/24993673/107884040-90f9d380-6ec0-11eb-9543-f1bf35df6c3a.png)

**Comment by lithiumtoast** [comment]
Nice!

Btw, I noticed for `sokol_gfx` you will need the `CBool` type. You can find it here: https://github.com/lithiumtoast/c2cs/blob/master/src/dotnet/projects/production/C2CS.Core/C2CS/C/CBool.cs

I'm still trying to figure out how to add this to generated C# files in a smart way...
